definitions:
  app.Response:
    properties:
      code:
        type: integer
      data: {}
      msg:
        type: string
    type: object
  v1.Url:
    properties:
      origin:
        type: string
      shorten:
        type: string
    required:
    - origin
    type: object
info:
  contact: {}
  description: 短网址服务
  title: dwz server
  version: "1.0"
paths:
  /api/v1/{shorten}:
    delete:
      parameters:
      - description: ShortenUrl
        in: path
        name: url
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      summary: Delete URL
    get:
      parameters:
      - description: ShortenUrl
        in: path
        name: url
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      summary: Get URL
  /api/v1/add:
    post:
      consumes:
      - application/json
      parameters:
      - description: OriginUrl
        in: body
        name: url
        required: true
        schema:
          $ref: '#/definitions/v1.Url'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      summary: Create URL
  /api/v1/jwt:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      security:
      - Bearer: []
      summary: Hello jwt
  /auth:
    post:
      parameters:
      - description: userName
        in: formData
        name: username
        required: true
        type: string
      - description: password
        in: formData
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      summary: Get Auth
  /hello:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      summary: Hello world
securityDefinitions:
  Bearer:
    in: header
    name: token
    type: apiKey
swagger: "2.0"
